[[constraint]]
  name = "k8s.io/kube-aggregator"
  branch = "release-1.6"
  source = "github.com/sttts/kube-aggregator"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.6"
  source = "github.com/sttts/apiserver"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.6"
  source = "github.com/sttts/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-3.0"
  source = "github.com/sttts/client-go"

[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "09691a3b6378b740595c1002f40c34dd5f218a22"

[[override]]
  name = "github.com/emicklei/go-restful-swagger12"
  version = "dcef7f55730566d41eae5db10e7d6981829720f6"

[[override]]
  name = "github.com/coreos/go-systemd"
  revision = "4484981625c1a6a2ecb40a390fcb6a9bcfee76e3"

# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
